# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GetSomeDataRequest" do
    optional :id, :int32, 1
  end
  add_message "GetSomeDataResponse" do
    optional :id, :int32, 1
    optional :name, :string, 2
    map :tags, :string, :string, 3
    repeated :interests, :message, 4, "Interest"
  end
  add_message "Interest" do
    optional :name, :string, 1
    optional :value, :string, 2
  end
end

GetSomeDataRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSomeDataRequest").msgclass
GetSomeDataResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSomeDataResponse").msgclass
Interest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Interest").msgclass
