# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: server_messages.proto for package ''

require 'grpc'
require 'server_messages_pb'

module MyAwesomeService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'MyAwesomeService'

    rpc :GetSomeData, GetSomeDataRequest, GetSomeDataResponse
  end

  Stub = Service.rpc_stub_class
end
