# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GetSomeDataRequest" do
    optional :id, :int32, 1
  end
  add_message "GetSomeDataResponse" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :tags, :message, 3, "Tags"
  end
  add_message "Tags" do
    map :tags, :string, :string, 1
  end
end

GetSomeDataRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSomeDataRequest").msgclass
GetSomeDataResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSomeDataResponse").msgclass
Tags = Google::Protobuf::DescriptorPool.generated_pool.lookup("Tags").msgclass
