// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_messages.proto

package server_messages

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSomeDataRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSomeDataRequest) Reset()         { *m = GetSomeDataRequest{} }
func (m *GetSomeDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetSomeDataRequest) ProtoMessage()    {}
func (*GetSomeDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a47ead99c57651, []int{0}
}

func (m *GetSomeDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSomeDataRequest.Unmarshal(m, b)
}
func (m *GetSomeDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSomeDataRequest.Marshal(b, m, deterministic)
}
func (m *GetSomeDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSomeDataRequest.Merge(m, src)
}
func (m *GetSomeDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetSomeDataRequest.Size(m)
}
func (m *GetSomeDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSomeDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSomeDataRequest proto.InternalMessageInfo

func (m *GetSomeDataRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetSomeDataResponse struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Interests            []*Interest       `protobuf:"bytes,4,rep,name=interests,proto3" json:"interests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSomeDataResponse) Reset()         { *m = GetSomeDataResponse{} }
func (m *GetSomeDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetSomeDataResponse) ProtoMessage()    {}
func (*GetSomeDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a47ead99c57651, []int{1}
}

func (m *GetSomeDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSomeDataResponse.Unmarshal(m, b)
}
func (m *GetSomeDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSomeDataResponse.Marshal(b, m, deterministic)
}
func (m *GetSomeDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSomeDataResponse.Merge(m, src)
}
func (m *GetSomeDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetSomeDataResponse.Size(m)
}
func (m *GetSomeDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSomeDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSomeDataResponse proto.InternalMessageInfo

func (m *GetSomeDataResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetSomeDataResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetSomeDataResponse) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetSomeDataResponse) GetInterests() []*Interest {
	if m != nil {
		return m.Interests
	}
	return nil
}

type Interest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interest) Reset()         { *m = Interest{} }
func (m *Interest) String() string { return proto.CompactTextString(m) }
func (*Interest) ProtoMessage()    {}
func (*Interest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a47ead99c57651, []int{2}
}

func (m *Interest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interest.Unmarshal(m, b)
}
func (m *Interest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interest.Marshal(b, m, deterministic)
}
func (m *Interest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interest.Merge(m, src)
}
func (m *Interest) XXX_Size() int {
	return xxx_messageInfo_Interest.Size(m)
}
func (m *Interest) XXX_DiscardUnknown() {
	xxx_messageInfo_Interest.DiscardUnknown(m)
}

var xxx_messageInfo_Interest proto.InternalMessageInfo

func (m *Interest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSomeDataRequest)(nil), "GetSomeDataRequest")
	proto.RegisterType((*GetSomeDataResponse)(nil), "GetSomeDataResponse")
	proto.RegisterMapType((map[string]string)(nil), "GetSomeDataResponse.TagsEntry")
	proto.RegisterType((*Interest)(nil), "Interest")
}

func init() { proto.RegisterFile("server_messages.proto", fileDescriptor_64a47ead99c57651) }

var fileDescriptor_64a47ead99c57651 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0x24, 0x15, 0x33, 0x05, 0x29, 0xd3, 0x0a, 0xa1, 0x07, 0x09, 0x41, 0x30, 0xa7,
	0x3d, 0x44, 0x41, 0xe9, 0x4d, 0x50, 0xc4, 0x83, 0x1e, 0xb6, 0xde, 0x65, 0xb5, 0x43, 0x08, 0x9a,
	0x6c, 0xdd, 0xd9, 0x46, 0xf2, 0x2b, 0xfd, 0x4b, 0xe2, 0x6a, 0x6b, 0xd5, 0xdc, 0x66, 0x77, 0xdf,
	0x7b, 0x7c, 0x6f, 0x07, 0x0e, 0x98, 0x6c, 0x4b, 0xf6, 0xa1, 0x26, 0x66, 0x5d, 0x12, 0xcb, 0xa5,
	0x35, 0xce, 0x64, 0x47, 0x80, 0xd7, 0xe4, 0xe6, 0xa6, 0xa6, 0x4b, 0xed, 0xb4, 0xa2, 0xd7, 0x15,
	0xb1, 0xc3, 0x7d, 0x08, 0xaa, 0x45, 0x22, 0x52, 0x91, 0x0f, 0x54, 0x50, 0x2d, 0xb2, 0x77, 0x01,
	0xe3, 0x5f, 0x32, 0x5e, 0x9a, 0x86, 0xe9, 0xaf, 0x0e, 0x11, 0xa2, 0x46, 0xd7, 0x94, 0x04, 0xa9,
	0xc8, 0x63, 0xe5, 0x67, 0x2c, 0x20, 0x72, 0xba, 0xe4, 0x24, 0x4c, 0xc3, 0x7c, 0x58, 0x1c, 0xca,
	0x9e, 0x1c, 0x79, 0xaf, 0x4b, 0xbe, 0x6a, 0x9c, 0xed, 0x94, 0xd7, 0xe2, 0x31, 0xc4, 0x55, 0xe3,
	0xc8, 0x12, 0x3b, 0x4e, 0x22, 0x6f, 0x8c, 0xe5, 0xcd, 0xf7, 0x8d, 0xfa, 0x79, 0x9b, 0x9e, 0x41,
	0xbc, 0xf1, 0xe2, 0x08, 0xc2, 0x67, 0xea, 0x3c, 0x4e, 0xac, 0x3e, 0x47, 0x9c, 0xc0, 0xa0, 0xd5,
	0x2f, 0xab, 0x35, 0xd0, 0xd7, 0x61, 0x16, 0x9c, 0x8b, 0xec, 0x14, 0xf6, 0xd6, 0x79, 0x1b, 0x6a,
	0xb1, 0x45, 0xdd, 0xeb, 0x2c, 0xee, 0x60, 0x74, 0xdb, 0x5d, 0xbc, 0x11, 0x9b, 0x9a, 0xe6, 0x64,
	0xdb, 0xea, 0x89, 0x70, 0x06, 0xc3, 0xad, 0x4a, 0x38, 0x96, 0xff, 0xff, 0x73, 0x3a, 0xe9, 0x6b,
	0x9d, 0xed, 0x3c, 0xee, 0xfa, 0x25, 0x9c, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xae, 0x78, 0xc4,
	0x87, 0x9d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyAwesomeServiceClient is the client API for MyAwesomeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyAwesomeServiceClient interface {
	GetSomeData(ctx context.Context, in *GetSomeDataRequest, opts ...grpc.CallOption) (*GetSomeDataResponse, error)
}

type myAwesomeServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyAwesomeServiceClient(cc *grpc.ClientConn) MyAwesomeServiceClient {
	return &myAwesomeServiceClient{cc}
}

func (c *myAwesomeServiceClient) GetSomeData(ctx context.Context, in *GetSomeDataRequest, opts ...grpc.CallOption) (*GetSomeDataResponse, error) {
	out := new(GetSomeDataResponse)
	err := c.cc.Invoke(ctx, "/MyAwesomeService/GetSomeData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyAwesomeServiceServer is the server API for MyAwesomeService service.
type MyAwesomeServiceServer interface {
	GetSomeData(context.Context, *GetSomeDataRequest) (*GetSomeDataResponse, error)
}

// UnimplementedMyAwesomeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMyAwesomeServiceServer struct {
}

func (*UnimplementedMyAwesomeServiceServer) GetSomeData(ctx context.Context, req *GetSomeDataRequest) (*GetSomeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSomeData not implemented")
}

func RegisterMyAwesomeServiceServer(s *grpc.Server, srv MyAwesomeServiceServer) {
	s.RegisterService(&_MyAwesomeService_serviceDesc, srv)
}

func _MyAwesomeService_GetSomeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSomeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAwesomeServiceServer).GetSomeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MyAwesomeService/GetSomeData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAwesomeServiceServer).GetSomeData(ctx, req.(*GetSomeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyAwesomeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MyAwesomeService",
	HandlerType: (*MyAwesomeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSomeData",
			Handler:    _MyAwesomeService_GetSomeData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_messages.proto",
}
